#1.使用yml文件有层级结构 缩进
#2.使用yml文件key value 之间使用 :号连接
#3.赋值时:号后边必须加空格
#=== 配置文件 ====
spring:
  profiles:
    active: dev
  jackson:
    time-zone: GMT+8
  #配置mvc页面
  mvc:
    view:
      prefix: /WEB-INF/
      suffix: .jsp
  data:
    redis:
      repositories:
        enabled: false

# === JPA配置 ====
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
#=== Redis配置 ====
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 100
        #最大阻塞等待时间(负数表示没限制)
        max-wait: 2000
        #最大空闲
        max-idle: 500
        #最小空闲
        min-idle: 8
    #连接超时时间
    timeout: 5000


#=================Mybatis配置=========================
# 别名配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  # xml扫描位置mybatis:
  mapper-locations: classpath*:mapper/*.xml

#mybatis-plush配置
#mybatis-plus:
#  #配置别名包
#  type-aliases-package: com.jt.pojo
#  #配置mapper映射
#  mapper-locations: classpath:/mybatis/mappers/*.xml
#  #开启驼峰映射
#  configuration:
#    map-underscore-to-camel-case: true

#添加日志输出
logging:
  level:
    com.jt.mapper: debug
